export const AUTH_SERVICE = 'AUTH_SERVICE';
export const USERS_SERVICE = 'USERS_SERVICE';
export const PRODUCTS_SERVICE = 'PRODUCTS_SERVICE';
export const ORDERS_SERVICE = 'ORDERS_SERVICE';
export const CART_SERVICE = 'CART_SERVICE';
export const STOCK_SERVICE = 'STOCK_SERVICE';
export const KAFKA_SERVICE = 'KAFKA_SERVICE';